---
driver:
  name: hyperv
  parent_vhd_folder: <%= ENV['HYPERV_BASE_IMAGE_FOLDER'] %>

transport:
  name: winrm
  password: <%= ENV['HYPERV_PASSWORD'] %>
  
verifier:
  name: pester

provisioner:
  name: dsc

platforms:
  - name: windows_2012r2_wmf4
    driver:
      parent_vhd_name: 'Windows2012R2-Base.vhd'

suites:
  - name: cWebsite_StartWebsite
  - name: cWebsite_StopWebsite
